// Shared static word-game data
window.GAME_STATIC_DATA = {
    countries: {
        A: ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan"],
        B: ["Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi"],
        C: ["Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic"],
        D: ["Denmark", "Djibouti", "Dominica", "Dominican Republic"],
        E: ["Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia"],
        F: ["Fiji", "Finland", "France"],
        G: ["Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana"],
        H: ["Haiti", "Honduras", "Hungary"],
        I: ["Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy"],
        J: ["Jamaica", "Japan", "Jordan"],
        K: ["Kazakhstan", "Kenya", "Kiribati", "Korea (North)", "Korea (South)", "Kosovo", "Kuwait", "Kyrgyzstan"],
        L: ["Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg"],
        M: ["Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar"],
        N: ["Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway"],
        O: ["Oman"],
        P: ["Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal"],
        Q: ["Qatar"],
        R: ["Romania", "Russia", "Rwanda"],
        S: ["Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria"],
        T: ["Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu"],
        U: ["Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan"],
        V: ["Vanuatu", "Vatican City", "Venezuela", "Vietnam"],
        W: ["None"],
        X: ["None"],
        Y: ["Yemen"],
        Z: ["Zambia", "Zimbabwe"]
    },
    foods: {
        A: ["Apple", "Avocado", "Artichoke", "Asparagus", "Almond", "Apricot", "Acorn Squash", "Amaranth", "Anchovy", "Arugula"],
        B: ["Banana", "Blueberry", "Broccoli", "Brussels Sprouts", "Bread", "Bagel", "Bacon", "Basil", "Blackberry", "Beet"],
        C: ["Carrot", "Cucumber", "Cabbage", "Cauliflower", "Celery", "Chili", "Cheese", "Chicken", "Chickpea", "Cilantro"],
        D: ["Dumpling", "Date", "Duck", "Dill", "Donut", "Dragonfruit", "Durian", "Dandelion Greens", "Danish", "Dosa"],
        E: ["Egg", "Eggplant", "Edamame", "Endive", "Escarole", "Eel", "Elderberry", "Emmental", "English Muffin", "Espresso"],
        F: ["Fish", "Fig", "Fennel", "Feta", "Falafel", "Focaccia", "French Fries", "Fudge", "Flan", "Frosting"],
        G: ["Grapes", "Garlic", "Ginger", "Gooseberry", "Gouda", "Granola", "Gnocchi", "Graham Cracker", "Guacamole", "Gumbo"],
        H: ["Hamburger", "Honey", "Hazelnut", "Hummus", "Haddock", "Halibut", "Hoisin Sauce", "Hot Dog", "Havarti", "Hash Browns"],
        I: ["Ice Cream", "Indian Curry", "Italian Sausage", "Iceberg Lettuce", "Idli", "Irish Soda Bread", "Iced Tea", "Instant Noodles", "Icing", "Italian Dressing"],
        J: ["Jam", "Jelly", "Jalapeno", "Jackfruit", "Jicama", "Jerky", "Juice", "Jellybean", "Jasmine Rice", "Jambalaya"],
        K: ["Kebab", "Kiwi", "Kale", "Ketchup", "Kimchi", "Kohlrabi", "Kombucha", "Kasha", "Kippers", "Kheer"],
        L: ["Lettuce", "Lemon", "Lime", "Lentil", "Lobster", "Lychee", "Lasagna", "Lollipop", "Linguine", "Liver"],
        M: ["Mango", "Mushroom", "Milk", "Muffin", "Macaroni", "Meatball", "Miso", "Mozzarella", "Meringue", "Melon"],
        N: ["Noodles", "Nutmeg", "Nectarine", "Naan", "Nachos", "Natto", "Nougat", "Nuggets", "Nicoise Salad", "Nori"],
        O: ["Orange", "Olive", "Onion", "Oregano", "Oatmeal", "Octopus", "Okra", "Omelette", "Orzo", "Oysters"],
        P: ["Pizza", "Pasta", "Peach", "Pear", "Pineapple", "Papaya", "Peanut", "Pepper", "Potato", "Pumpkin"],
        Q: ["Quiche", "Quinoa", "Quail", "Quesadilla", "Quince", "Quark", "Quahog", "Quenelle", "Quavers", "Quetsch"],
        R: ["Rice", "Raspberry", "Radish", "Raisin", "Rhubarb", "Ricotta", "Ravioli", "Ratatouille", "Ramen", "Roulade"],
        S: ["Salad", "Spinach", "Strawberry", "Sushi", "Sausage", "Soup", "Scone", "Salsa", "Saffron", "Schnitzel"],
        T: ["Taco", "Tomato", "Turkey", "Tofu", "Tangerine", "Tuna", "Turnip", "Tortilla", "Tiramisu", "Tapioca"],
        U: ["Udon", "Ugli Fruit", "Upside-Down Cake", "Urfa Pepper", "Ube", "Umami Paste", "Urad Dal", "Ukrainian Borscht", "Unagi", "Umeboshi"],
        V: ["Vanilla", "Vegetable", "Venison", "Vermicelli", "Vinegar", "Vichyssoise", "Victoria Sponge", "Vada", "Velveeta", "Vermouth"],
        W: ["Waffle", "Walnut", "Watermelon", "Wasabi", "Wheat", "Whipped Cream", "White Chocolate", "Wiener", "Wonton", "Worcestershire Sauce"],
        X: ["Xacuti", "Xigua", "Xylitol", "Xnipec", "Xouba", "Xingren", "Xocolatl", "Xiaolongbao", "Xerem", "Xerophyte"],
        Y: ["Yogurt", "Yam", "Yeast", "Yellowtail", "Yuzu", "Yabby", "Yakhni", "Yassa", "Yokan", "Yorkshire Pudding"],
        Z: ["Zucchini", "Ziti", "Zest", "Zander", "Zabaglione", "Zopf", "Zhoug", "Ziti Pasta", "Zinfandel", "Zebra Cake"]
    },
    drinks: {
        A: ["Apple Juice", "Apricot Nectar", "Aloe Vera Drink", "Amaretto", "Arnold Palmer", "Absinthe", "Aperol", "Apple Cider", "Aguardiente", "Akvavit"],
        B: ["Beer", "Black Tea", "Bubble Tea", "Buttermilk", "Bloody Mary", "Bourbon", "Brandy", "Baileys", "Bacardi", "Boba"],
        C: ["Coffee", "Coca-Cola", "Coconut Water", "Cranberry Juice", "Champagne", "Chai", "Cider", "Campari", "Cognac", "Cucumber Water"],
        D: ["Daiquiri", "Diet Coke", "Dr. Pepper", "Dry Martini", "Dubonnet", "Dandelion Tea", "Dark Beer", "Detox Water", "Dragonfruit Juice", "Dewberry Cordial"],
        E: ["Espresso", "Elderflower Cordial", "Eggnog", "Energy Drink", "Earl Grey Tea", "Ethanol", "Eiskaffee", "Elderberry Wine", "Evian", "Ethiopian Coffee"],
        F: ["Fanta", "Fruit Punch", "Fennel Tea", "Flat White", "Frappuccino", "Fernet", "Fizzy Water", "Frozen Margarita", "Frosty", "Frappe"],
        G: ["Ginger Ale", "Green Tea", "Grape Juice", "Gin", "Gimlet", "Grenadine", "Ginger Beer", "Grog", "Guava Juice", "Ginseng Tea"],
        H: ["Hot Chocolate", "Herbal Tea", "Horchata", "Hibiscus Tea", "Honey Mead", "Hefeweizen", "Hot Toddy", "Hurricane", "Hibiscus Water", "Hoppy Beer"],
        I: ["Iced Tea", "Irish Coffee", "Ice Water", "Indian Chai", "Iced Latte", "Italian Soda", "Ice Wine", "Iced Mocha", "Iced Cappuccino", "Iceberg"],
        J: ["Juice", "Jasmine Tea", "Julep", "Jagermeister", "Jamaica Water", "Jack Daniels", "Jalapeno Margarita", "Jasmine Milk Tea", "Jungle Juice", "Jolt Cola"],
        K: ["Kombucha", "Kahlua", "Kefir", "Kiwi Juice", "Kool-Aid", "Kava", "Kopi Luwak", "Kumquat Juice", "Kirin Beer", "Krupnik"],
        L: ["Lemonade", "Lime Juice", "Lassi", "Latte", "Long Island Iced Tea", "Lager", "Lychee Juice", "Lillet", "Lemon Water", "Limoncello"],
        M: ["Milk", "Mojito", "Matcha", "Margarita", "Mulled Wine", "Mimosa", "Milkshake", "Malibu", "Martini", "Mead"],
        N: ["Nectar", "Negroni", "Nut Milk", "Nettle Tea", "Nimbu Pani", "Nesquik", "Naked Juice", "Naranjilla Juice", "Nocino", "Nettle Beer"],
        O: ["Orange Juice", "Oolong Tea", "Ouzo", "Old Fashioned", "Oat Milk", "Orangina", "Ovaltine", "Oyster Shooter", "Ouzo Lemonade", "Oregon Chai"],
        P: ["Punch", "Pina Colada", "Peach Tea", "Peppermint Tea", "Port", "Prosecco", "Perrier", "Pomegranate Juice", "Pale Ale", "Pisco Sour"],
        Q: ["Quinine Water", "Quince Juice", "Qishr", "Quark Smoothie", "Quetsch", "Quince Wine", "Quark", "Quahog", "Quenelle", "Quavers"],
        R: ["Rum", "Raspberry Tea", "Root Beer", "Red Wine", "Rooibos Tea", "Raspberry Lemonade", "Raki", "Raspberry Smoothie", "Rhubarb Cordial", "Raspberry Vodka"],
        S: ["Soda", "Sangria", "Smoothie", "Scotch", "Seltzer", "Shirley Temple", "Sake", "Sambuca", "Sarsaparilla", "Sauvignon Blanc"],
        T: ["Tea", "Tonic Water", "Tomato Juice", "Tequila", "Turmeric Latte", "Thai Iced Tea", "Tamarind Juice", "Tisane", "Tangerine Juice", "Triple Sec"],
        U: ["Umeshu", "Ube Milkshake", "Uva Tea", "Ukrainian Vodka", "Uji Matcha", "Umeshu Soda", "Ube Latte", "Uva Juice", "Umeshu Cocktail", "Ube Smoothie"],
        V: ["Vodka", "Vanilla Milkshake", "Vermouth", "Vitamin Water", "V8 Juice", "Valpolicella", "Vanilla Latte", "Vinho Verde", "Violet Liqueur", "Vegan Smoothie"],
        W: ["Water", "Whiskey", "White Wine", "Wheatgrass Juice", "Warm Milk", "Winter Ale", "Wassail", "White Russian", "Whey Protein Shake", "Wild Berry Tea"],
        X: ["Xingren Almond Drink", "Xocolatl", "Xiaoshu Tea", "Xanadu Wine", "Xylitol Water", "Xingren Smoothie", "Xouba Juice", "Xerem Drink", "Xerophyte Tea", "Xigua Juice"],
        Y: ["Yakult", "Yerba Mate", "Yellow Tea", "Yogurt Drink", "Yunnan Coffee", "Yuzu Soda", "Yam Wine", "Yogurt Smoothie", "Yunnan Tea", "Yuzu Cocktail"],
        Z: ["Zinfandel", "Zobo Drink", "Zucchini Juice", "Zebra Milk", "Zinger Tea", "Zubrowka", "Zobo Punch", "Zinfandel Rose", "Zebra Smoothie", "Zesty Lemonade"]
    },
    animals: {
        A: ["Antelope", "Aardvark", "Albatross", "Alligator", "Anaconda", "Armadillo", "Axolotl", "Aye-Aye", "African Elephant", "Arctic Fox"],
        B: ["Bear", "Bison", "Baboon", "Bat", "Beaver", "Blue Whale", "Butterfly", "Buzzard", "Bald Eagle", "Barracuda"],
        C: ["Cat", "Cheetah", "Cobra", "Camel", "Capybara", "Chameleon", "Coyote", "Crab", "Crow", "Caterpillar"],
        D: ["Dog", "Dolphin", "Duck", "Deer", "Dragonfly", "Dodo", "Donkey", "Dugong", "Dhole", "Dachshund"],
        E: ["Elephant", "Eagle", "Eel", "Emu", "Egret", "Ermine", "Earthworm", "Eastern Bluebird", "Echidna", "Elk"],
        F: ["Fox", "Frog", "Falcon", "Flamingo", "Firefly", "Ferret", "Fiddler Crab", "Flying Squirrel", "Fossa", "Frigatebird"],
        G: ["Giraffe", "Goat", "Gorilla", "Gecko", "Goldfish", "Grasshopper", "Gannet", "Gazelle", "Gibbon", "Gila Monster"],
        H: ["Horse", "Hawk", "Hedgehog", "Heron", "Hippopotamus", "Honeybee", "Hornbill", "Hummingbird", "Hyena", "Harpy Eagle"],
        I: ["Iguana", "Indian Star Tortoise", "Indian Cobra", "Indian Elephant", "Indian Pangolin", "Indian Starling", "Indian Mongoose", "Indian Peafowl", "Indian Python", "Indian Starfish"],
        J: ["Jaguar", "Jellyfish", "Jackal", "Jackrabbit", "Japanese Macaque", "Javan Rhino", "Jungle Cat", "Junco", "Jerboa", "Jacana"],
        K: ["Kangaroo", "Koala", "Kookaburra", "Kudu", "Kiwi", "Kingfisher", "Kite", "Killer Whale", "Komodo Dragon", "Krill"],
        L: ["Lion", "Lemur", "Leopard", "Lynx", "Llama", "Lobster", "Ladybug", "Lamprey", "Leafcutter Ant", "Lungfish"],
        M: ["Monkey", "Moose", "Mongoose", "Manta Ray", "Manatee", "Mole", "Moth", "Macaw", "Magpie", "Mandrill"],
        N: ["Narwhal", "Newt", "Nightingale", "Numbat", "Nautilus", "Nile Crocodile", "Northern Cardinal", "Northern Pike", "Nudibranch", "Nutria"],
        O: ["Owl", "Octopus", "Otter", "Ocelot", "Orangutan", "Ostrich", "Ox", "Osprey", "Orca", "Okapi"],
        P: ["Penguin", "Panda", "Parrot", "Peacock", "Pelican", "Porcupine", "Puma", "Platypus", "Puffin", "Python"],
        Q: ["Quail", "Quokka", "Quetzal", "Queen Bee", "Quagga", "Quoll", "Quahog", "Quetzalcoatlus", "Quokka Wallaby", "Queen Triggerfish"],
        R: ["Rabbit", "Raccoon", "Rat", "Raven", "Red Panda", "Reindeer", "Rhinoceros", "Robin", "Rockhopper Penguin", "Rottweiler"],
        S: ["Snake", "Shark", "Sheep", "Sloth", "Snail", "Spider", "Swan", "Squirrel", "Starfish", "Seahorse"],
        T: ["Tiger", "Turtle", "Toucan", "Tarantula", "Tuna", "Turkey", "Termite", "Tortoise", "Tasmanian Devil", "Tapir"],
        U: ["Urial", "Umbrellabird", "Uakari", "Ugandan Kob", "Unicornfish", "Upland Sandpiper", "Urchin", "Ulysses Butterfly", "Umbrella Octopus", "Ural Owl"],
        V: ["Vulture", "Viper", "Vicuna", "Vervet Monkey", "Vinegaroon", "Velvet Worm", "Vampire Bat", "Vaquita", "Violet-backed Starling", "Vine Snake"],
        W: ["Wolf", "Whale", "Walrus", "Wombat", "Woodpecker", "Warthog", "Weasel", "Wildebeest", "Wolverine", "Wrasse"],
        X: ["Xerus", "Xantus's Hummingbird", "X-ray Tetra", "Xenopus", "Xenarthra", "Xenops", "Xenopus Frog", "Xenoturbella", "Xenopus Toad", "Xerus Squirrel"],
        Y: ["Yak", "Yellowjacket", "Yellowhammer", "Yellowfin Tuna", "Yellowtail Snapper", "Yellow Baboon", "Yellow Mongoose", "Yellow Warbler", "Yellow Tang", "Yellow Anaconda"],
        Z: ["Zebra", "Zebu", "Zorilla", "Zander", "Zebra Finch", "Zebra Shark", "Zebra Spider", "Zebra Swallowtail", "Zebra Mussel", "Zebra Dove"]
    }
};
